### ISSUE TITLE
Multimodal medical images as x input? 

### ISSUE THREAD

**Issue by astewartau** [MMIV-ML/fastMONAI#33]
Thanks for the hard work putting this together! It has been really useful for me.

Is it possible to provide a tuple of images to a datablock as the x value? 

I have:

```
dblock = MedDataBlock(
    blocks=(ImageTupleBlock(cls=MedImage), MedMaskBlock),
    splitter=RandomSplitter(),
    get_x=ColReader('qsm_files'),
    get_y=ColReader('seg_files'),
    item_tfms=[
        PadOrCrop([80, 80, 80]),
        RandomFlip(axes=("LR",)),
        RandomFlip(axes=("AP",)),
        RandomAffine(degrees=(90, 90, 90)),
        ZNormalization(),
    ],
    reorder=requires_resampling,
    resample=suggested_voxelsize
)
```

But instead of using `get_x=ColReader('qsm_files')`, I want to retrieve multiple medical images to learn from multimodal data. I do not see any example of this and am unsure how to approach it. Do you have any advice?

**Comment by lillepeder** [comment]
Hi astewartau,

What you are seeking is implemented. Assuming you have your paths in a pandas dataframe, you supply each entry in the image column with a semicolon-separated string of the paths of each modality.

Something akin to this:
`
'sub-x_T1.nii.gz;sub-x_QSM.nii.gz'
`

That should fix your problem.

**Comment by skaliy** [comment]
Thank you @astewartau! Glad that you have found the library useful! 
And thanks, @lillepeder, for answering the question. I hope this solution helps you for now. Please don't hesitate to reach out if you have any other questions. 

I have plans to implement a more elegant solution for handling tuples of images in DataBlock in the near future. :)

**Comment by astewartau** [comment]
It's been a while, but I have another question about this with multimodal inputs. 

If I'm using z-normalization, ie.,

```python
training_augmentations = [
    fastMONAI.vision_all.PadOrCrop([80, 80, 80]),
    fastMONAI.vision_all.RandomFlip(axes=("LR",)),
    fastMONAI.vision_all.RandomFlip(axes=("AP",)),
    fastMONAI.vision_all.RandomAffine(degrees=(90, 90, 90)),
    fastMONAI.vision_all.ZNormalization()
]

...

dls = fastMONAI.vision_all.DataLoaders.from_dblock(
    fastMONAI.vision_all.MedDataBlock(
        blocks=(fastMONAI.vision_all.ImageBlock(cls=fastMONAI.vision_all.MedImage), fastMONAI.vision_all.MedMaskBlock),
        splitter=fastMONAI.vision_all.IndexSplitter(valid_index),
        get_x=fastMONAI.vision_all.ColReader('in_files'),
        get_y=fastMONAI.vision_all.ColReader('seg_files'),
        item_tfms=training_augmentations,
        reorder=requires_resampling,
        resample=suggested_voxelsize
    ),
    df,
    bs=batch_size
)
```

Does the z-normalization apply to each input modality independently? Or does it normalize them together? This would be a problem if the input range of one modality is very different from the other, but they are normalized according to the full range.
